### ISSUE TITLE
[bug]点击中文页面`编辑此页`按钮，实际跳转的是英文版源码

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin-cookbook#140]
# Document Bug Report

**Document URL:**
https://starcoinorg.github.io/starcoin-cookbook/zh/docs/concepts/accumulator

**Describe the document's bug:**

在页面最下方点击[编辑此页]，实际跳转的是：https://github.com/starcoinorg/starcoin-cookbook/edit/main/docs/99-concepts/06-accumulator.md

**Other information:**

应该是跳转到中文版的md

**Comment by nkysg** [comment]
Thx. I think you can  fix it.

**Comment by jiangying000** [comment]
> Thx. I think you can fix it. @jiangying000

fixing, thank you for remaining me
