### ISSUE TITLE
Diem 链接 404 [bug]

### ISSUE THREAD

**Issue by v1xingyue** [starcoinorg/starcoin-cookbook#158]
# Document Bug Report

**Document URL:**

https://starcoinorg.github.io/starcoin-cookbook/zh/docs/move/deploy-first-move-contract

**Describe the document's bug:**

[Diem 区块链](https://github.com/deim/diem)  链接 404 了。

**Comment by geometryolife** [comment]
Dime 区块链已经成为历史了，链接可以去掉了。
