### ISSUE TITLE
External link availability detection

### ISSUE THREAD

**Issue by geometryolife** [starcoinorg/starcoin-cookbook#161]
另外看看能不能配置一个外部链接的可用性检测插件，把失效的链接自动检测出来。

_Originally posted by @jolestar in https://github.com/starcoinorg/starcoin-cookbook/issues/159#issuecomment-1200339900_

**Comment by jiangying000** [comment]
这个可供参考
https://github.com/move-language/move/runs/7602266027?check_suite_focus=true

**Comment by geometryolife** [comment]
https://github.com/starcoinorg/starcoin-cookbook/pull/163 找了一个action
