### ISSUE TITLE
[question]  starcoin_miner 启动时是否要求必须全量节点，完全同步状态，另外如果是snapshot导入的是否可行

### ISSUE THREAD

**Issue by jiangying000** [starcoinorg/starcoin-cookbook#174]
# Question

**Describe the Question**

我启动`starcoin_miner --user alice -n 4` 没有出现类似cookbook中描述的日志，搜索hash或者rate也没有结果
 https://github.com/starcoinorg/starcoin-cookbook/blob/7a08a2232e49a19b1be9299301dac4ce5d5969d4/i18n/zh/docusaurus-plugin-content-docs/current/02-getting-started/04-mining/01-mining.md?plain=1#L37-L45

### 问题1

是否挖矿时必须完全同步，要是全量节点

### 问题2

如果是snapshot导入的节点，是否可以挖矿，snapshot导入相关：#160

**Related Code**

**Additional Context**

**Comment by jolestar** [comment]
1. 对的
2. 可以
