### ISSUE TITLE
[bug] the highlighted content of the code block is not clear

### ISSUE THREAD

**Issue by nangongamo** [starcoinorg/starcoin-cookbook#187]
# Document Bug Report

**Document URL:**
涉及文档的所有 code 高亮内容。例如：https://starcoinorg.github.io/starcoin-cookbook/zh/docs/move/quick-start

**Describe the document's bug:**

在默认的浅色模式下，代码块高亮显示的bug（指定的代码块颜色高亮后，无法看清楚被高亮的代码块内容），暗黑模式下正常。

**Other information:**

**Comment by geometryolife** [comment]
Already fixed.
