### ISSUE TITLE
[doc] Move (getting started) troubleshooting document improvement for wsl2

### ISSUE THREAD

**Issue by ren-ryder** [starcoinorg/starcoin-cookbook#54]
https://starcoinorg.github.io/starcoin-cookbook/docs/getting-started/install/build

>>> for troubleshooting wsl2 ubuntu on windows pc, this solution fixed error:
error: linker `cc` not found   |   = note: No such file or directory (os error 2)

https://ostechnix.com/how-to-fix-rust-error-linker-cc-not-found-on-linux/
![image](https://user-images.githubusercontent.com/99104408/166847617-eb1c3f9b-06c4-44a4-ab69-9638680135ea.png)

**Comment by jolestar** [comment]
@geometryolife please help to improve the doc

**Comment by geometryolife** [comment]
> @geometryolife please help to improve the doc

ok，I'm adding.

**Comment by geometryolife** [comment]
> https://starcoinorg.github.io/starcoin-cookbook/docs/getting-started/install/build
> 
> > > > for troubleshooting wsl2 ubuntu on windows pc, this solution fixed error:
> > > > error: linker `cc` not found   |   = note: No such file or directory (os error 2)
> 
> https://ostechnix.com/how-to-fix-rust-error-linker-cc-not-found-on-linux/ ![image](https://user-images.githubusercontent.com/99104408/166847617-eb1c3f9b-06c4-44a4-ab69-9638680135ea.png)

Thanks for your suggestions for improvement, I have added the troubleshooting content to the common troubleshooting, and you can see it after the merge is published.

**Comment by ren-ryder** [comment]
<3
