### ISSUE TITLE
[doc] Is spectest same with integration-test ?

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-cookbook#73]
# Document Suggestion

**Describe the Suggestion**

文档 [how-to-debug](https://starcoinorg.github.io/starcoin-cookbook/zh/docs/move/move-test/how-to-debug) 中，使用了术语 `spectest` ， 从内容上看就是`integration-test`。而且 `mpm` 的子命令中没有 `spectest` 的， 所以 `spectest` 和 `integration-test` 是同一回事吗？ 这是因为该文档过时了吗？

**Comment by jolestar** [comment]
对，how to debug 需要更新一下
