### ISSUE TITLE
[Feature Request] Consider add a search bar which is able to search all docs in cookbook

### ISSUE THREAD

**Issue by djy0** [starcoinorg/starcoin-cookbook#77]
类似[vue官网](https://vuejs.org/)的这种搜索功能，这样用户遇到问题就可以比较快地通过检索找到相应文档了
![image](https://user-images.githubusercontent.com/23182033/168233041-529d7834-6dbc-4bdc-9640-a6633256fb37.png)

**Comment by djy0** [comment]
![https://aptos.dev/](https://user-images.githubusercontent.com/23182033/168390175-d312bd0a-08a8-449c-9f40-f845ad066078.jpg)

**Comment by jolestar** [comment]
这个 [Docusaurus](https://docusaurus.io/) 有插件支持，可以选择配置一个。  @geometryolife

**Comment by geometryolife** [comment]
> 这个 [Docusaurus](https://docusaurus.io/) 有插件支持，可以选择配置一个。 @geometryolife

👌
