### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by WhatsJay** [starcoinorg/starcoin-cookbook#82]
Can we have a community team set up to start to make the telegram and discord more active.

We need more activity. Regular chat's/games will bring more and more people to stc and gaon more traction.

We also need questions answered much faster and much more often but understand the team are busy and simply can not read through all the chat to answer all questions therefore with a community team you can have a manager who brings the main and obvious questions to your attention so they can be addressed and resolved as soon as possible.

**Comment by jolestar** [comment]
Please submit a detailed technical question, which we can write a document to resolve.
